#!/bin/bash
# will store only the free space in the variable
freespace=$(df -h / | grep -E "\/$" | awk '{print $4}')
greentext="\033[32m"
bold="\033[1m"
t_bold=$(tput bold)
t_greentext=$(tput setaf 2)
t_normal=$(tput sgr0)
normal="\033[0m"
logdate=$(date +"%Y%m%d")
logfile="$lodate"_report.log

echo -e $bold"Quick system report for "$greentext"$HOSTNAME"$normal
echo -e $t_bold"Author "$t_greentext"NOUROS"$t_normal
printf "\tSystem type:\t%s\n" $MACHTYPE
printf "\tBash Version:\t%s\n" $BASH_VERSION
printf "\tFree Space:\t%s\n" $freespace
printf "\tFiles in dir:\t%s\n" $(ls | wc -l)
printf "\tGenerated on:\t%s\n" $(date +"%m/%d/%y") # US date format
echo -e $greentext"A summary of this info has been saved to $logfile"$normal

cat <<- EOF > $logfile 
        This report was automatically generated by my Bash script.
        It contains a brief summary of some system information.
EOF


